// Code generated by ifacemaker; DO NOT EDIT.

package api

import (
	tgBotAPI "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	"github.com/wtkeqrf0/tg_form/internal/appeal"
)

// Api ...
type Api interface {
	Start(appeal appeal.Method)
	SendMe(chatID int64) (tgBotAPI.Chattable, error)
}
