// Code generated by ifacemaker; DO NOT EDIT.

package session

import (
	"context"

	"github.com/wtkeqrf0/tg_form/pkg/util"
)

// Session ...
type Session interface {
	Set(ctx context.Context, key string, payload *Payload) error
	SetValue(ctx context.Context, key string, fieldKey util.PayloadField, value any) error
	Get(ctx context.Context, key string) (*Payload, error)
	Delete(ctx context.Context, keys ...string) error
	Keys(ctx context.Context, key string) ([]string, error)
}
