// Code generated by ifacemaker; DO NOT EDIT.

package appeal

import (
	"context"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
)

// Method ...
type Method interface {
	ChooseDivisions(ctx context.Context, chatID int64) (tgbotapi.Chattable, error)
	SelectDivision(ctx context.Context, chatID int64, messageID int, value string) (tgbotapi.Chattable, error)
	StrForm(ctx context.Context, chatID int64, text string) (tgbotapi.Chattable, error)
	SendAppeal(ctx context.Context, chatID int64, messageID int, userName, value string) ([]tgbotapi.Chattable, error)
	SendFastReply(ctx context.Context, chatID int64, messageID int, appealID string) ([]tgbotapi.Chattable, error)
}
